name: Algolia Upload Records
on:
  [push]
jobs:
  algolia:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Upload Records
        uses: iChochy/Algolia-Upload-Records@main
        env:
          APPLICATION_ID: 6U9P7QAZFR
          ADMIN_API_KEY: ${{secrets.ALGOLIA_ADMIN_API_KEY}}
          INDEX_NAME: website
          FILE_PATH: docs/algolia.json