name: PR Preview

on: pull_request

jobs:
  deploy:
    name: Deploy Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: afc163/surge-preview@v1
        id: preview_step
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dist: packages/site/assets
          build: |
            yarn
            lerna exec --scope @zarm-design/cli -- yarn build
            lerna exec --scope site -- yarn build
      - name: Get the preview_url
        run: echo "url => ${{ steps.preview_step.outputs.preview_url }}"

  # comment:
  #   name: Update Status Comment
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Comment Preview URL
  #       uses: actions-cool/maintain-one-comment@v1.1.0
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         body: |
  #           [${{ steps.preview_step.outputs.preview_url }}](${{ steps.preview_step.outputs.preview_url }})
  #           <!-- AUTO_PREVIEW_HOOK -->
  #         body-include: '<!-- AUTO_PREVIEW_HOOK -->'
  #         number: ${{ github.event.number }}
  #     - name: Comment For Failed
  #       if: ${{ failure() }}
  #       uses: actions-cool/maintain-one-comment@v1.1.0
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         body: |
  #           Preview Site Deploy Failed!
  #           <!-- AUTO_PREVIEW_HOOK -->
  #         body-include: '<!-- AUTO_PREVIEW_HOOK -->'
  #         number: ${{ github.event.number }}
  #   needs: deploy
